baseURL = 'https://flaneur2020.github.io/'
languageCode = 'en-us'

title = "Flaneur2020"
theme = 'ritzy'
translationKey = 'about'
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.zh]
    weight = 2
    languageName = "中文"

[taxonomies]
tag = 'tags'
googleAnalytics = "G-xxxxxxxxx"

[params]
author = "Yazhou Li"
description = "A Tech Blog"
socialImage = "/images/bg-blog-header.jpg"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
